### Raw Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Retention_rate.csv")

In [4]:
df.head()

          cohort_month  months_since_first_order  retention_rate
0  2016-09-01 00:00:00                         0          1.0000
1  2016-10-01 00:00:00                         0          1.0000
2  2016-10-01 00:00:00                         1          0.0031
3  2016-10-01 00:00:00                         3          0.0031
4  2016-10-01 00:00:00                         5          0.0031

In [ ]:
## Average of all months retetions
df.groupby('months_since_first_order')['retention_rate'].agg(['mean','min','max'])*100

                                mean     min     max
months_since_first_order
0                         100.000000  100.00  100.00
1                           5.047727    0.11  100.00
2                           0.348500    0.03    0.67
3                           0.296111    0.09    0.61
4                           0.305882    0.02    0.65
5                           0.280625    0.13    0.53
6                           0.268667    0.11    0.52
7                           0.247857    0.05    0.62
8                           0.244615    0.13    0.62
9                           0.194545    0.05    0.31
10                          0.265000    0.11    0.39
11                          0.222000    0.07    0.35